services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: true
      VERSION: 1.21.1
      DIFFICULTY: normal
      ONLINE_MODE: false
      MOTD: Bienvenido
      SEED: 752695909913210178
      SERVER_NAME: AWSCRAFT
    volumes:
      - ./data:/data
